// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzyeingkpsvyjoczsxpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56eWVpbmdrcHN2eWpvY3pzeHBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NDU5MTgsImV4cCI6MjA3MjUyMTkxOH0.0xQZz-ltvppoQcpd9gxCutwCdRYcEl5bODWGNusbe3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});